# request
uint8 DIAGNOSTICS                    = 0
uint8 RESET_SENSOR                   = 1
uint8 DOWNLOAD_SNAPSHOT              = 2
uint8 SAVE_CONFIG                    = 3

time stamp
uint8 command

---
#response
time stamp
bool success
bool all_in_range
string[] parameters